name: Run MUnit Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: maven-settings-action
      uses: s4u/maven-settings-action@894661b3ddae382f1ae8edbeab60987e08cf0788 # commit hash references to v4.0.0
      with:
        servers: '[{"id": "mulesoft-ee-releases", "username": "${env.MULE_REPO_USER}", "password": "${env.MULE_REPO_PASSWORD}"}]'
        repositories: '[{"id": "mulesoft-ee-releases", "name": "MuleSoft EE Releases", "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"}]'

    - name: Build and optionally test when Mule EE secrets are available
      env:
        MULE_REPO_USER: ${{ secrets.MULE_REPO_USER }}
        MULE_REPO_PASSWORD: ${{ secrets.MULE_REPO_PASSWORD }}
      run: |
        if [[ -n "$MULE_REPO_USER" ]]; then
          mvn -B clean verify
        else
          echo "::notice file=build.yml,title=Skipping Tests::Mule EE secrets not found. Skipping tests after build."
          mvn -B clean install -DskipTests
        fi
